import { StyleSheet } from 'react-native';
import { borderRadius } from '../../../../shared/theme';

export const mkStyles = (colors: any) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    title: { fontSize: 18, fontWeight: '700', color: colors.text },
    subtitle: { fontSize: 12, color: colors.textSecondary, marginTop: 1 },
    scrollContent: { padding: 16 },
    loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    sectionLabel: { fontSize: 13, fontWeight: '600', color: colors.textSecondary, marginBottom: 6 },
    specialtiesRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 10 },
    specialtyChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: borderRadius.full,
      backgroundColor: colors.primary + '20',
    },
    specialtyChipText: { fontSize: 12, fontWeight: '600', color: colors.primary },
    specialtyInputRow: { flexDirection: 'row', gap: 8, marginBottom: 16, alignItems: 'center' },
    specialtyInput: {
      flex: 1,
      height: 42,
      borderRadius: borderRadius.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.inputBg,
      paddingHorizontal: 12,
      color: colors.text,
      fontSize: 14,
    },
    specialtyAddButton: {
      width: 42,
      height: 42,
      borderRadius: borderRadius.md,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    divider: { height: 1, backgroundColor: colors.divider, marginVertical: 20 },
    tempPasswordBox: {
      backgroundColor: colors.warning + '15',
      borderWidth: 1,
      borderColor: colors.warning + '40',
      borderRadius: borderRadius.md,
      padding: 14,
      marginBottom: 16,
      gap: 10,
    },
    tempPasswordLabel: { fontSize: 12, fontWeight: '600', color: colors.warning },
    tempPasswordRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    tempPasswordText: { fontSize: 18, fontWeight: '700', color: colors.text, letterSpacing: 1, flex: 1 },
    copyButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: borderRadius.md,
      backgroundColor: colors.warning + '25',
    },
    copyButtonText: { fontSize: 12, fontWeight: '600', color: colors.warning },
    actionsRow: { flexDirection: 'row', gap: 12, marginBottom: 16 },
    secondaryButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      height: 46,
      borderRadius: borderRadius.md,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    secondaryButtonText: { fontSize: 13, fontWeight: '600', color: colors.text },
  });
