import { StyleSheet } from 'react-native';
import { borderRadius, spacing } from '../../../../shared/theme';

export const mkStyles = (colors: any) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
    title: { fontSize: 18, fontWeight: '700', color: colors.text },
    subtitle: { fontSize: 12, color: colors.textSecondary, marginTop: 1 },
    addButton: {
      width: 36,
      height: 36,
      borderRadius: borderRadius.full,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    listContent: { paddingHorizontal: 16, flexGrow: 1 },
    loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: borderRadius.md,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      marginBottom: 8,
      gap: 12,
    },
    bikeNumberCircle: {
      width: 40, height: 40, borderRadius: 20,
      alignItems: 'center', justifyContent: 'center',
      backgroundColor: colors.background,
    },
    bikeNumberText: { fontSize: 15, fontWeight: '700', color: colors.primary },
    rowInfo: { flex: 1 },
    rowNotes: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
    badge: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: borderRadius.full },
    badgeText: { fontSize: 11, fontWeight: '600' },
    deleteButton: { padding: 6 },

    // Modal de adicionar/editar
    modalOverlay: { flex: 1, backgroundColor: 'rgba(10,5,25,0.90)', justifyContent: 'flex-end' },
    modalSheet: {
      backgroundColor: colors.card,
      borderTopLeftRadius: borderRadius.xl,
      borderTopRightRadius: borderRadius.xl,
      padding: spacing.md,
      paddingBottom: spacing.xl,
    },
    modalTitle: { fontSize: 16, fontWeight: '700', color: colors.text, marginBottom: 16 },
    statusOptionsRow: { flexDirection: 'row', gap: 8, marginBottom: 4 },
    statusOption: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 10,
      borderRadius: borderRadius.md,
      borderWidth: 1,
      borderColor: colors.border,
    },
    statusOptionText: { fontSize: 12, fontWeight: '600', color: colors.textSecondary },
    modalActions: { flexDirection: 'row', gap: 12, marginTop: 8 },
    modalCancelButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      height: 46,
      borderRadius: borderRadius.md,
      borderWidth: 1,
      borderColor: colors.border,
    },
    modalCancelText: { fontSize: 14, fontWeight: '600', color: colors.text },
  });
