import { StyleSheet } from 'react-native';
import { borderRadius } from '../../../shared/theme';

export const mkStyles = (colors: any) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    title: { fontSize: 18, fontWeight: '700', color: colors.text },
    confirmAllText: { fontSize: 13, fontWeight: '600', color: colors.primaryDark },
    sessionBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginHorizontal: 16,
      marginBottom: 16,
      padding: 14,
      borderRadius: borderRadius.md,
      borderWidth: 1,
    },
    sessionBannerIdle: {
      backgroundColor: colors.card,
      borderColor: colors.border,
    },
    sessionBannerActive: {
      backgroundColor: colors.success + '10',
      borderColor: colors.success,
    },
    sessionBannerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
    sessionBannerTitle: { fontSize: 14, fontWeight: '700', color: colors.text },
    sessionBannerSubtitle: { fontSize: 12, color: colors.textSecondary, marginTop: 1 },
    endSessionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: borderRadius.md,
      backgroundColor: colors.danger,
    },
    endSessionButtonText: { color: colors.white, fontWeight: '600', fontSize: 12 },
    startSessionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: borderRadius.md,
      backgroundColor: colors.primary,
    },
    startSessionButtonDisabled: {
      backgroundColor: colors.grayLight + '40',
    },
    startSessionButtonText: { color: colors.white, fontWeight: '600', fontSize: 12 },
    startSessionButtonTextDisabled: { color: colors.textSecondary },
    statsRow: { flexDirection: 'row', gap: 12, paddingHorizontal: 16, marginBottom: 16 },
    statBox: {
      flex: 1,
      backgroundColor: colors.card,
      padding: 12,
      borderRadius: borderRadius.md,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    statValue: { fontSize: 22, fontWeight: '700', color: colors.text },
    statLabel: { fontSize: 11, color: colors.textSecondary, marginTop: 2 },
    loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    loadingText: { fontSize: 16, color: colors.textSecondary },
    emptyState: { alignItems: 'center', marginTop: 60, gap: 8, paddingHorizontal: 32 },
    emptyText: { fontSize: 16, fontWeight: '600', color: colors.text, textAlign: 'center' },
    emptySubtext: { fontSize: 13, color: colors.textSecondary, textAlign: 'center' },
    listContent: { paddingHorizontal: 16, paddingBottom: 16, flexGrow: 1 },
    studentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      padding: 14,
      borderRadius: borderRadius.md,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 12,
    },
    studentRowPresent: {
      borderColor: colors.success,
      backgroundColor: colors.success + '08',
    },
    checkbox: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: colors.grayLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    checkboxActive: { backgroundColor: colors.success, borderColor: colors.success },
    studentAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    studentInfo: { flex: 1 },
    studentName: { fontSize: 15, fontWeight: '600', color: colors.text },
    studentDetail: { fontSize: 12, color: colors.textSecondary, marginTop: 1 },
  });
