import { StyleSheet } from 'react-native';
import { borderRadius } from '../../../shared/theme';

export const mkStyles = (colors: any) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    title: { fontSize: 18, fontWeight: '700', color: colors.text },
    scroll: { flex: 1 },
    content: { padding: 16, paddingBottom: 8 },
    sessionInfo: { alignItems: 'center', marginBottom: 24 },
    sessionName: { fontSize: 24, fontWeight: '700', color: colors.text, textAlign: 'center' },
    sessionStudio: { fontSize: 16, color: colors.textSecondary, marginTop: 4 },
    sessionInstructor: { fontSize: 14, color: colors.textSecondary, marginTop: 2 },
    timerContainer: { alignItems: 'center', marginBottom: 24 },
    timerLabel: { fontSize: 14, color: colors.textSecondary },
    timer: { fontSize: 48, fontWeight: '700', color: colors.text, marginTop: 4 },
    statsRow: { flexDirection: 'row', gap: 12, marginBottom: 24 },
    statBox: {
      flex: 1,
      backgroundColor: colors.card,
      padding: 16,
      borderRadius: borderRadius.lg,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    statValue: { fontSize: 28, fontWeight: '700', color: colors.text },
    statLabel: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
    studentList: { marginBottom: 8 },
    listTitle: { fontSize: 18, fontWeight: '700', color: colors.text, marginBottom: 12 },
    studentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      padding: 14,
      borderRadius: borderRadius.md,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 12,
    },
    studentAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    studentName: { flex: 1, fontSize: 15, fontWeight: '500', color: colors.text },
    statusIndicator: { width: 12, height: 12, borderRadius: 6 },
    actions: {
      gap: 12,
      padding: 16,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.background,
    },
    actionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 16,
      borderRadius: borderRadius.lg,
      gap: 8,
    },
    actionButtonText: { color: colors.white, fontWeight: '600', fontSize: 16 },
  });
