import { StyleSheet } from 'react-native';
import { borderRadius, shadow } from '../../../shared/theme';

export const mkStyles = (colors: any) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    title: { fontSize: 18, fontWeight: '700', color: colors.text },
    loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12, paddingHorizontal: 32 },
    loadingText: { fontSize: 16, color: colors.textSecondary },
    errorTitle: { fontSize: 16, fontWeight: '600', color: colors.text, textAlign: 'center' },
    retryButton: { backgroundColor: colors.primaryDark, paddingHorizontal: 20, paddingVertical: 10, borderRadius: borderRadius.md, marginTop: 4 },
    retryButtonText: { color: colors.white, fontWeight: '600', fontSize: 14 },
    scrollContent: { padding: 16, paddingBottom: 40 },
    cardsRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
    metricCard: {
      flex: 1,
      backgroundColor: colors.card,
      padding: 16,
      borderRadius: borderRadius.lg,
      borderLeftWidth: 4,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadow.sm,
    },
    metricValue: { fontSize: 28, fontWeight: '700', color: colors.text },
    metricLabel: { fontSize: 13, color: colors.textSecondary, marginTop: 4 },
    sectionTitle: { fontSize: 18, fontWeight: '700', color: colors.text, marginTop: 20, marginBottom: 16 },
    barChart: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'flex-end',
      backgroundColor: colors.card,
      padding: 16,
      borderRadius: borderRadius.lg,
      borderWidth: 1,
      borderColor: colors.border,
    },
    occupancyChart: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'flex-end',
      backgroundColor: colors.card,
      padding: 16,
      borderRadius: borderRadius.lg,
      borderWidth: 1,
      borderColor: colors.border,
    },
    chartEmptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: colors.card,
      padding: 24,
      borderRadius: borderRadius.lg,
      borderWidth: 1,
      borderColor: colors.border,
    },
    chartEmptyText: {
      fontSize: 13,
      color: colors.textSecondary,
      textAlign: 'center',
    },
    barColumn: { alignItems: 'center', gap: 4 },
    barValue: { fontSize: 12, fontWeight: '600', color: colors.text },
    barTrack: { height: 80, justifyContent: 'flex-end' },
    bar: { width: 24, backgroundColor: colors.primaryDark, borderRadius: 4 },
    occupancyTrack: { height: 100, justifyContent: 'flex-end' },
    occupancyBar: { width: 20, backgroundColor: colors.primary, borderRadius: 4 },
    barLabel: { fontSize: 10, color: colors.textSecondary },
    infoCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primaryDark + '10',
      padding: 16,
      borderRadius: borderRadius.lg,
      marginTop: 20,
      gap: 10,
    },
    infoText: { flex: 1, fontSize: 13, color: colors.textSecondary, lineHeight: 18 },
  });
