import { StyleSheet } from 'react-native';
import { borderRadius } from '../../../shared/theme';

export const mkStyles = (colors: any) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
      paddingHorizontal: 20, paddingTop: 16, paddingBottom: 12,
      backgroundColor: colors.card, borderBottomWidth: 1, borderBottomColor: colors.border,
    },
    headerLeft: { flex: 1 },
    title: { fontSize: 28, fontWeight: '700', color: colors.text },
    subtitle: { fontSize: 15, color: colors.textSecondary, marginTop: 4 },
    scroll: { paddingHorizontal: 16, paddingBottom: 32 },
    statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    statCard: {
      width: '47%',
      backgroundColor: colors.card,
      borderRadius: borderRadius.lg,
      padding: 16,
      borderLeftWidth: 3,
      borderWidth: 1,
      borderColor: colors.border,
      minHeight: 100,
    },
    statIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
    },
    statValue: { fontSize: 20, fontWeight: '700', color: colors.text },
    statTitle: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
    section: { marginTop: 24 },
    sectionTitle: { fontSize: 18, fontWeight: '700', color: colors.text, marginBottom: 12 },
    sectionHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
    sectionMeta: { fontSize: 13, color: colors.textSecondary, marginTop: -8, marginBottom: 0 },
    yearSelector: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      borderRadius: borderRadius.full,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 4,
      paddingVertical: 2,
      gap: 2,
    },
    yearBtn: { padding: 6 },
    yearLabel: { fontSize: 15, fontWeight: '700', color: colors.text, minWidth: 48, textAlign: 'center' },
    activity: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.card,
      padding: 12,
      borderRadius: borderRadius.md,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 10,
    },
    activityDot: { width: 8, height: 8, borderRadius: 4 },
    activityText: { fontSize: 14, color: colors.text, flex: 1 },
    chartCard: {
      backgroundColor: colors.card,
      borderRadius: borderRadius.lg,
      paddingVertical: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    chartRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 6, paddingHorizontal: 12 },
    barColumn: { width: 52, alignItems: 'center' },
    barValue: { fontSize: 10, fontWeight: '600', color: colors.textSecondary, marginBottom: 4 },
    barTrack: {
      height: 120,
      width: '100%',
      justifyContent: 'flex-end',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    bar: { width: 22, backgroundColor: colors.primary, borderTopLeftRadius: 4, borderTopRightRadius: 4 },
    barLabel: { fontSize: 11, color: colors.textSecondary, marginTop: 6 },
    chartEmpty: {
      backgroundColor: colors.card,
      borderRadius: borderRadius.lg,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 32,
      alignItems: 'center',
      gap: 10,
    },
    chartEmptyText: { fontSize: 14, color: colors.textSecondary },
    loading: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    loadingText: { fontSize: 16, color: colors.textSecondary },
  });
