import { StyleSheet } from 'react-native';
import { borderRadius } from '../../../../shared/theme';

export const mkStyles = (colors: any) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scrollContent: { paddingBottom: 40 },
  heroSection: { alignItems: 'center', paddingVertical: 32, paddingHorizontal: 20 },
  heroTitle: { fontSize: 28, fontWeight: '700', color: colors.text, marginTop: 16 },
  heroSubtitle: { fontSize: 16, color: colors.textSecondary, textAlign: 'center', marginTop: 8, lineHeight: 22 },
  statsRow: {
    flexDirection: 'row',
    backgroundColor: colors.card,
    marginHorizontal: 16,
    borderRadius: borderRadius.lg,
    padding: 20,
    justifyContent: 'space-around',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statBox: { alignItems: 'center', flex: 1 },
  statDivider: { width: 1, backgroundColor: colors.border },
  statValue: { fontSize: 32, fontWeight: '700', color: colors.primary },
  statLabel: { fontSize: 13, color: colors.textSecondary, marginTop: 4 },
  codeSection: { paddingHorizontal: 16, marginBottom: 20 },
  codeLabel: { color: colors.textSecondary, fontSize: 14, marginBottom: 8 },
  codeBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: borderRadius.lg,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.primary,
    borderStyle: 'dashed',
  },
  codeText: { color: colors.primary, fontSize: 22, fontWeight: '700', letterSpacing: 2 },
  howItWorks: { paddingHorizontal: 16, marginBottom: 24 },
  howTitle: { color: colors.text, fontSize: 18, fontWeight: '700', marginBottom: 16 },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: borderRadius.md,
    padding: 14,
    marginBottom: 8,
    gap: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  stepIcon: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.md,
    backgroundColor: colors.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepTitle: { color: colors.text, fontSize: 15, fontWeight: '600' },
  stepDesc: { color: colors.textSecondary, fontSize: 13, marginTop: 2 },
  shareButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.primary,
    marginHorizontal: 16,
    borderRadius: borderRadius.lg,
    padding: 18,
    gap: 8,
  },
  shareText: { color: colors.black, fontSize: 18, fontWeight: '700' },
});
