import { StyleSheet } from 'react-native';
import { borderRadius } from '../../../../shared/theme';

export const mkStyles = (colors: any) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scrollContent: { paddingBottom: 40 },
  cartBadge: { position: 'relative', padding: 4 },
  badge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: colors.danger,
    borderRadius: 10,
    width: 18,
    height: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: { color: colors.white, fontSize: 10, fontWeight: '700' },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.text,
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  loadingText: { color: colors.textSecondary, textAlign: 'center', marginTop: 40 },
  pkgCard: {
    backgroundColor: colors.card,
    borderRadius: borderRadius.xl,
    marginHorizontal: 16,
    marginVertical: 6,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
  },
  pkgCardPopular: {
    borderColor: colors.primary,
    borderWidth: 2,
  },
  popularBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: borderRadius.sm,
    marginBottom: 12,
  },
  popularText: { color: colors.black, fontSize: 11, fontWeight: '700' },
  pkgHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  pkgName: { fontSize: 18, fontWeight: '700', color: colors.text },
  pkgPrice: { fontSize: 22, fontWeight: '700', color: colors.primary },
  pkgDetails: { marginTop: 8, flexDirection: 'row', gap: 16 },
  pkgCredits: { fontSize: 14, color: colors.textSecondary },
  pkgPerCredit: { fontSize: 14, color: colors.success },
  pkgFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  pkgValidity: { fontSize: 13, color: colors.textSecondary },
});
